name: workflow
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      dynamodb:
        image: amazon/dynamodb-local
        options: >-
          --health-cmd "curl --fail -X POST http://127.0.0.1:8000 -H 'Accept-Encoding: identity' -H 'Authorization: AWS4-HMAC-SHA256 Credential=AKIAXXXXXXXXXXXXXXXX/20190505/ap-southeast-2/dynamodb/aws4_request, SignedHeaders=accept-encoding;cache-control;content-type;user-agent;x-amz-date;x-amz-target, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' -H 'Content-Type: application/json' -H 'User-Agent: postman' -H 'X-Amz-Date: 20190505T235951Z' -H 'X-Amz-Target: DynamoDB_20120810.ListTables' -H 'cache-control: no-cache' -d '{}' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Prepare
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
        env:
          DYNAMO_TYPES_ENDPOINT: http://dynamodb:8000
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        # npm will not execute `prepublisnOnly` lifecycle hook if user is root.
        # @see https://github.com/semantic-release/semantic-release/issues/956#issuecomment-431097773
        run: |
          npm run prepublishOnly
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
